name: 'Send email'

on:
    workflow_dispatch:
    schedule:
        - cron: '0 5-15/3 * * 1-5'

jobs:
    email:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [lts/*]

        steps:
            - uses: hmarr/debug-action@v3
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Send email
              run: |
                  yarn
                  yarn send-email
              env:
                  EMAIL_TO: ${{ secrets.EMAIL_TO }}
                  EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
                  ALERTS_PAGE: ${{ secrets.ALERTS_PAGE }}
                  EMAIL_SUBJECT: ${{ secrets.EMAIL_SUBJECT }}
                  DATE_SELECTOR: ${{ secrets.DATE_SELECTOR }}
                  ALERTS_SELECTOR: ${{ secrets.ALERTS_SELECTOR }}
                  CHILD_CLASSNAME: ${{ secrets.CHILD_CLASSNAME }}
                  SENDINBLUE_API_KEY: ${{ secrets.SENDINBLUE_API_KEY }}
